services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - TEMPORAL_TARGET=host.docker.internal:7233
      - TASK_QUEUE=hello-python-tq
    ports:
      - "7233:7233"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
