# Override for local development
# This file is automatically used by docker-compose when present
services:
  worker:
    environment:
      # Use localhost for local Temporal server
      - TEMPORAL_TARGET=host.docker.internal:7233
    # Enable hot reload for development
    volumes:
      - ./app:/app/app:ro
    # Restart policy for development
    restart: unless-stopped

  image-service:
    # Enable hot reload for development  
    volumes:
      - "/mnt/c/Users/jeric/Documents/ComfyUI/models:/comfyui-models:ro"
      - ./generated_images:/output
      - ./image_generation_service.py:/app/image_generation_service.py:ro
    # Restart policy for development
    restart: unless-stopped

  # Optional: Add local Temporal service for complete local development
  temporal:
    image: temporalio/auto-setup:1.20.0
    ports:
      - "7233:7233"
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
    depends_on:
      - postgresql
    volumes:
      - temporal-data:/etc/temporal/config/dynamicconfig
    profiles:
      - local-temporal

  # Temporal Web UI (separate container)
  temporal-ui:
    image: temporalio/ui:2.10.3
    ports:
      - "8233:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    depends_on:
      - temporal
    profiles:
      - local-temporal

  postgresql:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
      POSTGRES_DB: temporal
    volumes:
      - postgres-data:/var/lib/postgresql/data
    profiles:
      - local-temporal

volumes:
  temporal-data:
  postgres-data: 